### ISSUE TITLE
Expire headers

### ISSUE THREAD

**Issue by fbjork** [jacquescrocker/jammit-s3#2]
Any chance of getting expire headers support added?

**Comment by jacquescrocker** [comment]
definitely. can you take a look and post a patch? i'll merge asap

**Comment by fbjork** [comment]
I'll have a look at it and submit a pull request

**Comment by jigardoshi** [comment]
I am hoping this change would include a "Cache-Control" header as well.

**Comment by kmamykin** [comment]
Cache-Control support is already there, just define s3_cache_control config setting like this:
s3_cache_control: public, max-age=<%= 365 \* 24 \* 60 \* 60 %>

**Comment by jumph4x** [comment]
Was the expires header ever added? I don't see it. 

Should we reopen the issue? let me know if you'd like a pull request.
