### ISSUE TITLE
already initialized constant ...

### ISSUE THREAD

**Issue by kredmer** [jacquescrocker/jammit-s3#26]
I get a lot of warning of already initialized constants - see here: https://gist.github.com/1496980

gemfile.lock

```
jammit (0.6.5)
  yui-compressor (>= 0.9.3)
jammit-s3 (0.6.0.2)
  jammit (>= 0.5.4)
  mimemagic (>= 0.1.7)
  s3 (>= 0.3.7)
```

I played with nearly all combinations in gemfile to solve this problem.

If I only use jammit there is no warning - so it must be in jammit-s3.

Any ideas?

**Comment by kmamykin** [comment]
Its a wild guess here, but do you have both jammit and jammit-s3 declared in Gemfile?
jammit-s3 already depends on jammit, and I remember there was an issue when declaring both gems. 
Try with just 
gem 'jammit-s3'

**Comment by kredmer** [comment]
yes, I tried with just 
gem 'jammit-s3'
....

**Comment by kredmer** [comment]
OK. I found the solution.

in routes.rb I had still still line : require 'jammit'

Removing it - removed the warning.
