### ISSUE TITLE
Gem conflict with paperclip

### ISSUE THREAD

**Issue by sheab** [jacquescrocker/jammit-s3#5]
Hey, I already am using paperclip in my app, and it needs the aws-s3 gem.

jammit-s3 wants just the s3 gem, when I try to launch my app with
gem 'aws-s3'
gem 'jammit-s3'
gem 'paperclip'
i get "/Users/shea/.rvm/gems/ruby-1.9.2-p0/gems/aws-s3-0.6.2/lib/aws/s3/extensions.rb:206:in `const_missing_from_s3_library': uninitialized constant AWS::S3::Connection (NameError)"

adding gem 's3' does not help

**Comment by cameronyule** [comment]
The s3 gem has it's own Paperclip extension as an alternative to using aws-s3 if that helps?

**Comment by sheab** [comment]
I'm an idiot - didn't realize that aws-s3 wasn't the only s3 gem that paperclip could use

thanks, using just the s3 gem fixed it.

**Comment by joshcutler** [comment]
I am having the same issue.  I was wondering what version of the gems you were using, because I could not get paperclip to work with just hte s3 gem

**Comment by cameronyule** [comment]
@joshcutler Are you using the library file that comes with the s3 gem?

https://github.com/qoobaa/s3/blob/master/extra/s3_paperclip.rb
