### ISSUE TITLE
not getting prompted for credentials

### ISSUE THREAD

**Issue by jjb** [jacquescrocker/jammit-s3#6]
I followed the instructions in the readme. When I invoke `bundle exec jammit-s3` in my rails 2 project, i get:

```
➔ bundle exec jammit-s3
access_key_id: '' is not valid
bundle exec jammit-s3  45.15s user 2.06s system 189% cpu 24.954 total
```

I though it might be a conflict with paperclip and/or aws-s3, I took those out, didn't help.

Let me know if you would like more info.

Thanks for jammit-s3!

**Comment by jacquescrocker** [comment]
basically its just not picking up the access_key_id setting. do you have it defined in your assets.yml or elsewhere?

**Comment by jjb** [comment]
I don't have it defined but the readme says "Every time you run jammit-s3 it will ask you for your Amazon credentials." — Is this old information?

thanks

**Comment by jacquescrocker** [comment]
hmm, yes, this is old. i used to have highline in there, but it was too heavy a dependency

I'll fix the README now

**Comment by jjb** [comment]
okay got it. so i'm not crazy :)
